#!/bin/bash
KB_HOME=/home/zhangle/ileler/.rc-ubuntu.local/bins/.linux/kibana/kibana-6.3.1-linux-x86_64
KB_OUT=$KB_HOME/kb.out
KB_PID=$KB_HOME/kb.pid
chown zhangle $KB_OUT $KB_PID
if [ -f $KB_PID ]; then kill -9 `cat $KB_PID` && read -p shutdown... -t 6; fi
su zhangle -c "nohup $KB_HOME/bin/kibana > $KB_OUT 2>&1 & echo \$! > $KB_PID"
cat $KB_PID && tail -f $KB_OUT
