#!/bin/bash
egrep "^$1" /etc/passwd >& /dev/null
if [[ -z $1 || $? -eq 1 ]]
then
    echo user [$1] does not exist.
    exit 1;
fi
RUN_WITH=$1
ZOO_HOME=/u~u/.rc-ubuntu.local/bins/.linux/zookeeper/.zookeeper
ZOO_OUT=$ZOO_HOME/zk.out
ZOO_PID=$ZOO_HOME/zk.pid
ZOO_LOG_DIR=$ZOO_HOME/zk.log
mkdir -p $ZOO_LOG_DIR;chown -R $RUN_WITH $ZOO_HOME/
if [ -f $ZOO_PID ]; then kill -9 `cat $ZOO_PID` && read -p shutdown... -t 6; fi
su $RUN_WITH -c "export ZOO_LOG_DIR=$ZOO_LOG_DIR;nohup $ZOO_HOME/bin/zkServer.sh start-foreground > $ZOO_OUT 2>&1 & echo \$! > $ZOO_PID"
echo -e \\nnew pid: `cat $ZOO_PID` && tail -f $ZOO_OUT
